//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoStore.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moto_photos
    {
        public int Id { get; set; }
        public int id_moto { get; set; }
        public string photo_url { get; set; }
    
        public virtual Motorcycle Motorcycle { get; set; }
    }
}
