//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoStore.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motorcycle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Motorcycle()
        {
            this.Moto_photos = new HashSet<Moto_photos>();
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public string make { get; set; }
        public string type { get; set; }
        public int year_of_issue { get; set; }
        public double engine_capacity { get; set; }
        public int number_of_cilindrs { get; set; }
        public bool isABS { get; set; }
        public bool isElectrostarter { get; set; }
        public bool isCruizeControl { get; set; }
        public string description { get; set; }
        public int number_of_models { get; set; }
        public double price { get; set; }
        public string main_photo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Moto_photos> Moto_photos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
