//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoStore.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int id_moto { get; set; }
        public int id_user { get; set; }
        public int id_shop { get; set; }
        public bool status { get; set; }
        public string adress { get; set; }
    
        public virtual Motorcycle Motorcycle { get; set; }
        public virtual Shop_information Shop_information { get; set; }
        public virtual User User { get; set; }
    }
}
